from __future__ import annotations

from importlib import import_module

__all__ = [
    "ConfigFile",
    "base_config_schema",
    "compose_config_schema",
    "generate_config_schema",
    "load_project_extras_schema",
    "strict_object",
    "string_schema",
    "integer_schema",
    "boolean_schema",
    "host_value_schema",
    "secret_value_schema",
    "UnsPacket",
    "DataPayload",
    "TablePayload",
    "isoformat",
    "RUNTIME_METADATA",
    "SecretResolverOptions",
    "InfisicalResolverOptions",
    "HostResolverOptions",
    "resolve_infisical_config",
    "UnsMqttClient",
    "StatusMonitor",
    "UnsMqttProxy",
    "MessageMode",
    "UnsProxyProcess",
    "UnsProxyProcessSync",
    "UnsProcessParameters",
    "UnsParameters",
    "UnsMqttProxySync",
    "UnsClient",
    "UnsClientManager",
    "AccessTokenProvider",
    "ServiceTokenProvider",
    "register_uns_client",
    "get_uns_client",
    "delete_uns_client",
    "AuthClient",
    "RawResponse",
    "RangeQuery",
    "RangeResult",
    "BatchRangeTopicResult",
    "BatchRangeResponse",
    "LastValueResult",
    "ClientError",
    "RuntimeServiceDescriptor",
    "RuntimeServiceRegistration",
    "RuntimeServiceRegistrationClient",
    "register_service",
    "SecureStore",
    "SecureStoreFactory",
    "FileStore",
    "UnsProxy",
    "EventEmitter",
    "TopicBuilder",
    "matches_topic_filter",
    "build_uns_identity_path",
    "build_uns_route_path",
    "configure_logger",
    "get_logger",
    "State",
]

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "ConfigFile": ("uns_kit.core.config_file", "ConfigFile"),
    "base_config_schema": ("uns_kit.core.config_schema", "base_config_schema"),
    "compose_config_schema": ("uns_kit.core.config_schema", "compose_config_schema"),
    "generate_config_schema": ("uns_kit.core.config_schema", "generate_config_schema"),
    "load_project_extras_schema": ("uns_kit.core.config_schema", "load_project_extras_schema"),
    "strict_object": ("uns_kit.core.config_schema", "strict_object"),
    "string_schema": ("uns_kit.core.config_schema", "string_schema"),
    "integer_schema": ("uns_kit.core.config_schema", "integer_schema"),
    "boolean_schema": ("uns_kit.core.config_schema", "boolean_schema"),
    "host_value_schema": ("uns_kit.core.config_schema", "host_value_schema"),
    "secret_value_schema": ("uns_kit.core.config_schema", "secret_value_schema"),
    "UnsPacket": ("uns_kit.core.packet", "UnsPacket"),
    "DataPayload": ("uns_kit.core.packet", "DataPayload"),
    "TablePayload": ("uns_kit.core.packet", "TablePayload"),
    "isoformat": ("uns_kit.core.packet", "isoformat"),
    "RUNTIME_METADATA": ("uns_kit.core.runtime_metadata", "RUNTIME_METADATA"),
    "SecretResolverOptions": ("uns_kit.core.secret_resolver", "SecretResolverOptions"),
    "InfisicalResolverOptions": ("uns_kit.core.secret_resolver", "InfisicalResolverOptions"),
    "HostResolverOptions": ("uns_kit.core.secret_resolver", "HostResolverOptions"),
    "resolve_infisical_config": ("uns_kit.core.secret_resolver", "resolve_infisical_config"),
    "UnsMqttClient": ("uns_kit.core.client", "UnsMqttClient"),
    "StatusMonitor": ("uns_kit.core.status_monitor", "StatusMonitor"),
    "UnsMqttProxy": ("uns_kit.core.uns_mqtt_proxy", "UnsMqttProxy"),
    "MessageMode": ("uns_kit.core.uns_mqtt_proxy", "MessageMode"),
    "UnsProxyProcess": ("uns_kit.core.proxy_process", "UnsProxyProcess"),
    "UnsProxyProcessSync": ("uns_kit.core.proxy_process_sync", "UnsProxyProcessSync"),
    "UnsProcessParameters": ("uns_kit.core.proxy_process", "UnsProcessParameters"),
    "UnsParameters": ("uns_kit.core.proxy_process", "UnsParameters"),
    "UnsMqttProxySync": ("uns_kit.core.proxy_process_sync", "UnsMqttProxySync"),
    "UnsClient": ("uns_kit.core.datahub_client", "UnsClient"),
    "UnsClientManager": ("uns_kit.core.datahub_client", "UnsClientManager"),
    "AccessTokenProvider": ("uns_kit.core.service_token_provider", "AccessTokenProvider"),
    "ServiceTokenProvider": ("uns_kit.core.service_token_provider", "ServiceTokenProvider"),
    "register_uns_client": ("uns_kit.core.datahub_client", "register_uns_client"),
    "get_uns_client": ("uns_kit.core.datahub_client", "get_uns_client"),
    "delete_uns_client": ("uns_kit.core.datahub_client", "delete_uns_client"),
    "AuthClient": ("uns_kit.core.auth_client", "AuthClient"),
    "RawResponse": ("uns_kit.core.datahub_client", "RawResponse"),
    "RangeQuery": ("uns_kit.core.datahub_client", "RangeQuery"),
    "RangeResult": ("uns_kit.core.datahub_client", "RangeResult"),
    "BatchRangeTopicResult": ("uns_kit.core.datahub_client", "BatchRangeTopicResult"),
    "BatchRangeResponse": ("uns_kit.core.datahub_client", "BatchRangeResponse"),
    "LastValueResult": ("uns_kit.core.datahub_client", "LastValueResult"),
    "ClientError": ("uns_kit.core.datahub_client", "ClientError"),
    "RuntimeServiceDescriptor": ("uns_kit.core.runtime_service_registration", "RuntimeServiceDescriptor"),
    "RuntimeServiceRegistration": ("uns_kit.core.runtime_service_registration", "RuntimeServiceRegistration"),
    "RuntimeServiceRegistrationClient": ("uns_kit.core.runtime_service_registration", "RuntimeServiceRegistrationClient"),
    "register_service": ("uns_kit.core.runtime_service_registration", "register_service"),
    "SecureStore": ("uns_kit.core.secure_store", "SecureStore"),
    "SecureStoreFactory": ("uns_kit.core.secure_store", "SecureStoreFactory"),
    "FileStore": ("uns_kit.core.secure_store", "FileStore"),
    "UnsProxy": ("uns_kit.core.proxy", "UnsProxy"),
    "EventEmitter": ("uns_kit.core.events", "EventEmitter"),
    "TopicBuilder": ("uns_kit.core.topic_builder", "TopicBuilder"),
    "matches_topic_filter": ("uns_kit.core.topic_matcher", "matches_topic_filter"),
    "build_uns_identity_path": ("uns_kit.core.uns_path", "build_uns_identity_path"),
    "build_uns_route_path": ("uns_kit.core.uns_path", "build_uns_route_path"),
    "configure_logger": ("uns_kit.core.logger", "configure_logger"),
    "get_logger": ("uns_kit.core.logger", "get_logger"),
    "State": ("uns_kit.core.state", "State"),
}


def __getattr__(name: str):
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_path, attr_name = target
    module = import_module(module_path)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
